### ISSUE TITLE
`docs` build failing on `main`

### ISSUE THREAD

**Issue by talonchandler** [czbiohub-sf/iohub#250] opened 2024-09-26 23:52 UTC
@ziw-liu I'm getting pydantic-related docs failures on `main`. FWIW I was able to build docs locally.  
```
    ../examples/run_multi_fov_hcs_ome_zarr.py failed leaving traceback:

    Traceback (most recent call last):
      File "/tmp/tmp7n6sm1z8/2397afb16e86aa6e071f74a7ea7ce906a24486f6/docs/examples/run_multi_fov_hcs_ome_zarr.py", line 17, in <module>
        from iohub.ngff import open_ome_zarr
      File "/tmp/tmp7n6sm1z8/2397afb16e86aa6e071f74a7ea7ce906a24486f6/iohub/__init__.py", line 9, in <module>
        from iohub.ngff import open_ome_zarr
      File "/tmp/tmp7n6sm1z8/2397afb16e86aa6e071f74a7ea7ce906a24486f6/iohub/ngff.py", line 17, in <module>
        from iohub.display_utils import channel_display_settings
      File "/tmp/tmp7n6sm1z8/2397afb16e86aa6e071f74a7ea7ce906a24486f6/iohub/display_utils.py", line 6, in <module>
        from iohub.ngff_meta import ChannelMeta, WindowDict
      File "/tmp/tmp7n6sm1z8/2397afb16e86aa6e071f74a7ea7ce906a24486f6/iohub/ngff_meta.py", line 153, in <module>
        class TransformationMeta(MetaBase):
      File "/tmp/tmp7n6sm1z8/2397afb16e86aa6e071f74a7ea7ce906a24486f6/iohub/ngff_meta.py", line 164, in TransformationMeta
        def no_extra_method(cls, values: dict):
      File "/home/runner/.local/lib/python3.10/site-packages/pydantic/deprecated/class_validators.py", line 234, in root_validator
        return root_validator()(*__args)  # type: ignore
      File "/home/runner/.local/lib/python3.10/site-packages/pydantic/deprecated/class_validators.py", line 240, in root_validator
        raise PydanticUserError(
    pydantic.errors.PydanticUserError: If you use `@root_validator` with pre=False (the default) you MUST specify `skip_on_failure=True`. Note that `@root_validator` is deprecated and should be replaced with `@model_validator`.
```

**Comment by ziw-liu** [comment] 2024-09-27 04:58
Duplicate of #239.

**Closed by ziw-liu** 2024-09-27 04:58 UTC
Labels: documentation
